pipeline {
    agent any

    stages {
        stage('check out') {
            steps {
                echo 'checking out code1 ...'
                sh 'git clone git@github.com:Planb0731/jenkins_demo.git'
            }
        }
    }
}